### ISSUE TITLE
Not working,

### ISSUE THREAD

**Issue by ghost** [C0nw0nk/Garrys-Mod-Fake-Players#1]
Set up correctly and still dosnt work

**Comment by ghost** [comment]
[ERROR] A runtime error has occurred in "gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua" on line 441.
The best help I can give you is this:

There is a player with an invalid team!

The player's name is Bot01, their team number is "1002", which has the name "Spectator"

Hints:
    - It is the server owner's responsibility to figure out why that player has no valid team.
    - This error is very likely to be caused by an earlier error. If you don't see any errors in your own console. Look at the server console.

The responsibility for the error above lies with (the authors of) one (or more) of these files:
    1. gamemodes/darkrp/gamemode/modules/base/sh_createitems.lua on line 441
    2. gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua on line 674
------- End of Simplerr error -------

**Comment by Ethorbit** [comment]
This isn't an error with the script, this is an error with your DarkRP job.
If you still need help friend me on steam and then give me the darkrp modification custom job's code and I can fix it for you.
http://steamcommunity.com/id/Ethorbit/

I used to own a DarkRP server with many custom jobs.

**Comment by C0nw0nk** [comment]
Run the sciprt on darkrp without any modules / addons then add your addons in to see what is causing the conflict exactly but given the fact the error is not coming from my script it seems a addon in your game mode does not recognize the spectator team.

Change the team from spectator to the following
`Team_to_Assign_Bots = false`

And see if that solves your problem then you know you have a problem with the game mode or other addon on your server recognizing spectators
