### ISSUE TITLE
Showing bots

### ISSUE THREAD

**Issue by ghost** [C0nw0nk/Garrys-Mod-Fake-Players#3]
Is there anyway to stop it from showing the number of bots on a server? So they look like real actual players

**Comment by C0nw0nk** [comment]
Are you talking in the server browser or while connected to the server.

**Comment by ghost** [comment]
The browser

**Comment by C0nw0nk** [comment]
Then you gotta dive into the land of C++ and as i wrote here.

https://github.com/C0nw0nk/Garrys-Mod-Fake-Players/blob/master/addons/fakeplayers/lua/autorun/server/sv_fakeplayers.lua#L21-L21

https://developer.valvesoftware.com/wiki/Server_queries#A2S_INFO

This script is not intended to be for spoofing packets to the steam master server and its LUA the closest you may get with LUA to such a thing could be with the player meta tables but packet spoofing and IP redirects on cloned servers is how everyone else does it what you will find is not written in LUA.

**Comment by C0nw0nk** [comment]
As an example clone your server onto other machines or IP's buy a bunch of Virtual private servers

And put some code like this on them. (This is for a Cloned server to become an IP redirect)

```
hook.Add("PlayerAuthed", "PlayerAuthed-NetSend", function(ply)
ply:SendLua("RunConsoleCommand('connect', '192.168.0.1:27015')")
end)
```

From what I recall allot of run console commands got blocked with an update so you may be best creating a shared file in this directory.
**_gmod/lua/autorun/_**
Name the file : **_redirect.lua_**

File contents can be this : 

```
if CLIENT then
RunConsoleCommand("connect", "192.168.0.1:27015")
end
```

There are multiple ways to go about doing it but it seems you are seeking a packet spoofer.

**Comment by Lebofly** [comment]
Seems that using a C++ module no longer works on the main server list for Garry's Mod. C++ Module: 
https://github.com/DuckyC/gmsv_query

**Comment by C0nw0nk** [comment]
I am sure if not Ducky but someone else will either update it with a new method to spoof packets until it gets fixed properly, Unless this time it was fixed properly it has happened a few times before they update to prevent it and another method comes out doing the exact same thing.

**Comment by Lebofly** [comment]
Don't think it was fixed properly as other servers are still doing the same, do they modify the payload in attempt at fixing it?

**Comment by C0nw0nk** [comment]
Depends on the method they use to block it this time you can edit ducky's code and compile it and see if that works and have a stab in the dark to figure out what way they are preventing it this time round.

Just be aware that Steam/Valve get IP's of servers that do this reported to them and will blacklist them ontop of the fact Garry's Mod has it's own blacklist that if you was to report server IP's doing that to them they get banned/blacklisted.

I suggest contacting Ducky and asking him if it is the same Ducky I remember from the facepunch forum this should be his account. https://facepunch.com/member.php?u=497020 Or you can post on his GitHub you referenced above and outline the issue.

**Comment by CLEVELANDMAN99** [comment]
any updates on this?
