### ISSUE TITLE
Player Count

### ISSUE THREAD

**Issue by SamJ135** [C0nw0nk/Garrys-Mod-Fake-Players#4]
The bots spawn in fine but on the menu when you are looking at different servers, although there are 22 bots in the server it still says 0/32. what should i do?

**Comment by C0nw0nk** [comment]
In-Game browser will look like that it filters out bots from being displayed in counts how ever if you click on the server it shows the list of all the players currently in the server.

Steam server browser displays normally. Does not filter that.
