### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by tylerfoxable** [C0nw0nk/Garrys-Mod-Fake-Players#5]
I dont understand it does not fill up the player slots but instead the bot slots why is this?

**Comment by C0nw0nk** [comment]
Well they are bots as it even says in the read me file, NextBOT and BOT console command can be used. It kicks the bots as players join, If a player leaves or disconnects times out etc it will spawn a bot in their place, If the player count is to lower than the threshold you specify it will spawn bots to fill up those slots or if the player count is higher than the threshold you specify then the server won't have any bots in it and will only be full of legitimate players. It keeps the player list looking full and can be used to make the bots play as real players etc, It's priority job is to populate the server with bots to play with.

**Comment by tylerfoxable** [comment]
Is it possible to make players seem as if there online and as like a fake player counter because all this is doing is showing bots on bots tab via legacy browser

Get Outlook for iOS

On Mon, Jul 11, 2016 at 7:28 AM -0500, "C0nw0nk" notifications@github.com wrote:

Well they are bots as it even says in the read me file, NextBOT and BOT console command can be used. It kicks the bots as players join, If a player leaves or disconnects times out etc it will spawn a bot in their place, If the player count is to lower than the threshold you specify it will spawn bots to fill up those slots or if the player count is higher than the threshold you specify then the server won't have any bots in it and will only be full of legitimate players. It keeps the player list looking full and can be used to make the bots play as real players etc, It's priority job is to populate the server with bots to play with.

**Comment by C0nw0nk** [comment]
The Garry's Mod browser intentionally filters bots from being displayed in the player count number but upon viewing a server it lists and displays all the bots with their fake names fine, With legit players already connected that's all you need, The steam browser on the other hand will display player counts with out filtering bots out. It is why packet spoofers that spoof the A2S_INFO packets to the steam master server that are just IP redirects are what all the fake servers are using now, Maybe soon that will go depending on what Valve/Steam do to prevent it, Some people on the Garry's Mod forum proposed ways for it to be fixed to stop fake payer counts and servers from being listed on the server list a few of those are already in place, Last I checked they already blacklist those IP's that spoof / fake packets making this script a safer option unless you want your IP's and the servers they point to blacklisted.

**Comment by tylerfoxable** [comment]
Would you mind joining my ts: ts.unitedgamerscommunity.com to bettee help me understand this problem its very important to me

Get Outlook for iOS

On Mon, Jul 11, 2016 at 7:28 AM -0500, "C0nw0nk" notifications@github.com wrote:

Well they are bots as it even says in the read me file, NextBOT and BOT console command can be used. It kicks the bots as players join, If a player leaves or disconnects times out etc it will spawn a bot in their place, If the player count is to lower than the threshold you specify it will spawn bots to fill up those slots or if the player count is higher than the threshold you specify then the server won't have any bots in it and will only be full of legitimate players. It keeps the player list looking full and can be used to make the bots play as real players etc, It's priority job is to populate the server with bots to play with.
